
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'branch_nick': 'stable/diablo',
    'revision_id': '5e7c88026ef59580951b9289bade5c6a97572a1f',
    'revno': 1063
}
